ALTER TABLE notification_preferences
  ADD COLUMN IF NOT EXISTS event_recap     BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS league_rank     BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS chat_mention    BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS rivalry_result  BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS level_up        BOOLEAN NOT NULL DEFAULT true;
